// Code generated by MockGen. DO NOT EDIT.
// Source: internal/storage/storage.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/sourcecd/gofermart/internal/models"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// AccrualSystemPoll mocks base method.
func (m *MockStore) AccrualSystemPoll(ctx context.Context, orders *[]int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AccrualSystemPoll", ctx, orders)
	ret0, _ := ret[0].(error)
	return ret0
}

// AccrualSystemPoll indicates an expected call of AccrualSystemPoll.
func (mr *MockStoreMockRecorder) AccrualSystemPoll(ctx, orders interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AccrualSystemPoll", reflect.TypeOf((*MockStore)(nil).AccrualSystemPoll), ctx, orders)
}

// AccrualSystemSave mocks base method.
func (m *MockStore) AccrualSystemSave(ctx context.Context, accrual []models.Accrual) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AccrualSystemSave", ctx, accrual)
	ret0, _ := ret[0].(error)
	return ret0
}

// AccrualSystemSave indicates an expected call of AccrualSystemSave.
func (mr *MockStoreMockRecorder) AccrualSystemSave(ctx, accrual interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AccrualSystemSave", reflect.TypeOf((*MockStore)(nil).AccrualSystemSave), ctx, accrual)
}

// AuthUser mocks base method.
func (m *MockStore) AuthUser(ctx context.Context, reg *models.User) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AuthUser", ctx, reg)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AuthUser indicates an expected call of AuthUser.
func (mr *MockStoreMockRecorder) AuthUser(ctx, reg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AuthUser", reflect.TypeOf((*MockStore)(nil).AuthUser), ctx, reg)
}

// CreateDatabaseScheme mocks base method.
func (m *MockStore) CreateDatabaseScheme(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDatabaseScheme", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateDatabaseScheme indicates an expected call of CreateDatabaseScheme.
func (mr *MockStoreMockRecorder) CreateDatabaseScheme(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDatabaseScheme", reflect.TypeOf((*MockStore)(nil).CreateDatabaseScheme), ctx)
}

// CreateOrder mocks base method.
func (m *MockStore) CreateOrder(ctx context.Context, userid, orderid int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrder", ctx, userid, orderid)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateOrder indicates an expected call of CreateOrder.
func (mr *MockStoreMockRecorder) CreateOrder(ctx, userid, orderid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrder", reflect.TypeOf((*MockStore)(nil).CreateOrder), ctx, userid, orderid)
}

// GetBalance mocks base method.
func (m *MockStore) GetBalance(ctx context.Context, userid int64, balance *models.Balance) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBalance", ctx, userid, balance)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetBalance indicates an expected call of GetBalance.
func (mr *MockStoreMockRecorder) GetBalance(ctx, userid, balance interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBalance", reflect.TypeOf((*MockStore)(nil).GetBalance), ctx, userid, balance)
}

// GetSecurityKey mocks base method.
func (m *MockStore) GetSecurityKey(ctx context.Context) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSecurityKey", ctx)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSecurityKey indicates an expected call of GetSecurityKey.
func (mr *MockStoreMockRecorder) GetSecurityKey(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSecurityKey", reflect.TypeOf((*MockStore)(nil).GetSecurityKey), ctx)
}

// InitializeSecurityKey mocks base method.
func (m *MockStore) InitializeSecurityKey(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InitializeSecurityKey", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// InitializeSecurityKey indicates an expected call of InitializeSecurityKey.
func (mr *MockStoreMockRecorder) InitializeSecurityKey(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InitializeSecurityKey", reflect.TypeOf((*MockStore)(nil).InitializeSecurityKey), ctx)
}

// ListOrders mocks base method.
func (m *MockStore) ListOrders(ctx context.Context, userid int64, orderList *[]models.Order) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListOrders", ctx, userid, orderList)
	ret0, _ := ret[0].(error)
	return ret0
}

// ListOrders indicates an expected call of ListOrders.
func (mr *MockStoreMockRecorder) ListOrders(ctx, userid, orderList interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOrders", reflect.TypeOf((*MockStore)(nil).ListOrders), ctx, userid, orderList)
}

// RegisterUser mocks base method.
func (m *MockStore) RegisterUser(ctx context.Context, reg *models.User) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterUser", ctx, reg)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RegisterUser indicates an expected call of RegisterUser.
func (mr *MockStoreMockRecorder) RegisterUser(ctx, reg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterUser", reflect.TypeOf((*MockStore)(nil).RegisterUser), ctx, reg)
}

// Withdraw mocks base method.
func (m *MockStore) Withdraw(ctx context.Context, userid int64, withdraw *models.Withdraw) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Withdraw", ctx, userid, withdraw)
	ret0, _ := ret[0].(error)
	return ret0
}

// Withdraw indicates an expected call of Withdraw.
func (mr *MockStoreMockRecorder) Withdraw(ctx, userid, withdraw interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Withdraw", reflect.TypeOf((*MockStore)(nil).Withdraw), ctx, userid, withdraw)
}

// Withdrawals mocks base method.
func (m *MockStore) Withdrawals(ctx context.Context, userid int64, withdrawals *[]models.Withdrawals) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Withdrawals", ctx, userid, withdrawals)
	ret0, _ := ret[0].(error)
	return ret0
}

// Withdrawals indicates an expected call of Withdrawals.
func (mr *MockStoreMockRecorder) Withdrawals(ctx, userid, withdrawals interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Withdrawals", reflect.TypeOf((*MockStore)(nil).Withdrawals), ctx, userid, withdrawals)
}
